#!/usr/bin/env sh

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##############################################################################

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"

warn () {
    echo "$*"
}

die () {
    echo
    echo "$*" >&2
    echo
    exit 1
}

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`"/$link"
  fi
done
SAVED="`pwd`"
cd "`dirname "$PRG"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME\n\nPlease set the JAVA_HOME variable in your environment to match the\nlocation of your Java installation."
    fi
else
    JAVACMD="java"
fi

# Increase the maximum file descriptors if we can.
MAX_FD="maximum"

case "$OSTYPE" in
  cygwin*|msys*|mingw*)
    # no-op
  ;;
  darwin*)
    # Increase the maximum file descriptors on macOS
    MAX_FD_LIMIT=`ulimit -H -n`
    if [ "$MAX_FD_LIMIT" != "unlimited" ] ; then
      ulimit -n "$MAX_FD_LIMIT" >/dev/null 2>&1
    fi
  ;;
  *)
    MAX_FD_LIMIT=`ulimit -H -n`
    if [ $? -eq 0 ]; then
      if [ "$MAX_FD_LIMIT" = "unlimited" ]; then
        MAX_FD="$MAX_FD_LIMIT"
      else
        ulimit -n "$MAX_FD_LIMIT" >/dev/null 2>&1
      fi
    fi
  ;;
esac

if [ "$MAX_FD" != "maximum" ] ; then
  ulimit -n "$MAX_FD" >/dev/null 2>&1
  if [ $? -ne 0 ]; then
    warn "Could not set maximum file descriptor limit: $MAX_FD"
  fi
fi

# For Darwin, add options to specify how the application appears in the dock
if [ "$OSTYPE" = "darwin" ] ; then
  GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
fi

# For Cygwin or MSYS, switch paths to Windows format before running java
if [ "$OSTYPE" = "cygwin" -o "$OSTYPE" = "msys" -o "$OSTYPE" = "mingw" ] ; then
  APP_HOME=`cygpath --path --mixed "$APP_HOME"`
  CLASSPATH=`cygpath --path --mixed "$CLASSPATH"`
  JAVACMD=`cygpath --unix "$JAVACMD"`
fi

# Escape application args
save () {
    for i in "$@" ; do
        printf %s\\n "$i" | sed "s/'/'\\''/g"
    done
}
APP_ARGS=`save "$@"`

# Collect all arguments for the java command, following the shell quoting and substitution rules
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$APP_ARGS"

exec "$JAVACMD" "$@"
