name: Bug report
description: Report a problem with ModGen
title: "[Bug] "
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: What happened?
  - type: textarea
    attributes:
      label: Steps to reproduce
  - type: textarea
    attributes:
      label: Expected behavior
  - type: textarea
    attributes:
      label: Screenshots or logs
