name: Feature request
description: Suggest an enhancement or new feature
title: "[Feature] "
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Description
      description: What do you want to see added?
  - type: textarea
    attributes:
      label: Why is it useful?
  - type: textarea
    attributes:
      label: Possible implementation
